// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpdcdP5_C4tm_3v41OACytowOyDczrUc',
    appId: '1:365106345715:web:751dcb2ec41679053b2986',
    messagingSenderId: '365106345715',
    projectId: 'dhava-91034',
    authDomain: 'dhava-91034.firebaseapp.com',
    storageBucket: 'dhava-91034.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDWMLWsP3gy_OP5ItoF1Kl7svo4yE25A',
    appId: '1:365106345715:android:6cad961d92d0f3e43b2986',
    messagingSenderId: '365106345715',
    projectId: 'dhava-91034',
    storageBucket: 'dhava-91034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpdjsng1tJJgX_q5ODL2-39ZB1Zx9JOk',
    appId: '1:365106345715:ios:1f17f399c5fcc7e03b2986',
    messagingSenderId: '365106345715',
    projectId: 'dhava-91034',
    storageBucket: 'dhava-91034.firebasestorage.app',
    androidClientId: '365106345715-44bto1n60oag13b1tlcu1hqvftguqhol.apps.googleusercontent.com',
    iosClientId: '365106345715-07ltatg0334kcdbj5uvapadcg3q7tgh1.apps.googleusercontent.com',
    iosBundleId: 'com.app.coherentEndurance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPpdjsng1tJJgX_q5ODL2-39ZB1Zx9JOk',
    appId: '1:365106345715:ios:1f17f399c5fcc7e03b2986',
    messagingSenderId: '365106345715',
    projectId: 'dhava-91034',
    storageBucket: 'dhava-91034.firebasestorage.app',
    androidClientId: '365106345715-44bto1n60oag13b1tlcu1hqvftguqhol.apps.googleusercontent.com',
    iosClientId: '365106345715-07ltatg0334kcdbj5uvapadcg3q7tgh1.apps.googleusercontent.com',
    iosBundleId: 'com.app.coherentEndurance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpdcdP5_C4tm_3v41OACytowOyDczrUc',
    appId: '1:365106345715:web:274e79fdd785e6da3b2986',
    messagingSenderId: '365106345715',
    projectId: 'dhava-91034',
    authDomain: 'dhava-91034.firebaseapp.com',
    storageBucket: 'dhava-91034.firebasestorage.app',
  );
}
